### PR TITLE
A few bits and pieces with haxe3 that might help

### PR DESCRIPTION
**Pull request by 0b1kn00b**

### CODE REVIEW

**Comment by sonygod** [comment]
haxe 3 build your version still get huge error..
src/tink/macro/tools/Printer.hx:101: characters 12-30 : Unmatched patterns: constraints.length = _
src/tink/macro/build/Member.hx:161: characters 11-12 : Unmatched patterns: AMacro
src/tink/lang/macros/Forward.hx:159: characters 31-122 : Invalid arguments
src/tink/lang/macros/Forward.hx:159: characters 31-122 : Function 'func' requires arguments : 
......

**Comment by 0b1kn00b** [comment]
which compiler revision?

**Comment by back2dos** [comment]
Unfortunately I already had my own fixes locally, but thank you for the effort!

**Comment by sonygod** [comment]
@0b1
version: haxe_r5884

**Pull request closed without merging**
